# Generated by Django 3.2.12 on 2023-11-09 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='Image',
        ),
    ]
