# Generated by Django 3.2.12 on 2023-11-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_remove_blogs_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
