# Generated by Django 3.2.12 on 2023-11-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_blogs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Image',
            field=models.ImageField(default=11, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
